name: surat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.5
  page_transition: ^2.0.4
  motion_toast: ^1.5.0
  fluttertoast: ^8.0.8
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.7
  image_picker: ^0.8.4+1
  html: ^0.15.0
  url_launcher: ^6.0.18
  dio: ^4.0.4
  file_picker: ^4.4.0
  path: ^1.8.0
  intl: ^0.17.0
  skeleton_animation: ^0.1.4
  lottie: ^1.2.2
  flutter_easyloading: ^3.0.3
  flutter_shimmer: ^2.1.2
  simple_time_range_picker: ^0.0.4
  syncfusion_flutter_datepicker: ^19.4.56
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  carousel_slider: ^4.1.1
  fancy_bottom_navigation: ^0.3.3
  google_nav_bar: ^5.0.6
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^9.5.1
  firebase_messaging_platform_interface: ^3.2.0
  syncfusion_flutter_calendar: ^19.4.56
  image_cropper: ^2.0.3
  flutter_search_bar: ^2.1.0
  multi_select_flutter: ^4.1.2
  timeline_tile: ^2.0.0
  calendar_view: ^0.0.5
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/email.png
    - images/login2.jpg
    - images/regisform.png
    - images/security.png
    - images/emailconfirm.png
    - images/welcome.jpg
    - images/baby.png
    - images/thumb.png
    - images/person.png
    - images/userprof.png
    - images/paper.png
    - images/ktp.png
    - images/warning.png
    - images/alert.png
    - images/noconnection.png
    - images/forgotpass.png
    - images/logout.png
    - images/kalendar.png
    - images/location.png
    - images/waiting.png
    - images/inprocess.png
    - images/done.png
    - images/store.png
    - images/money.png
    - images/scull.png
    - images/briefcase.png
    - images/paycheck.png
    - images/flag.png
    - images/gear.png
    - images/airplane.png
    - images/question.png
    - images/info.png
    - images/logo.png
    - images/staff.png
    - images/archive.png
    - images/profilepic.png
    - images/noimage.png
    - assets/loading-circle.json
    - assets/loading-hourglass.json
    - images/panitia.png
    - images/bendesa.png
    - images/handshake.png
    - images/validation.png
    - images/letter-closed.png
    - images/letter-open.png
    - images/penerima.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Times New Roman
      fonts:
        - asset: fonts/times.ttf
        - asset: fonts/timesbd.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
