// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBigAdyBB1uAtrXxnbnFdHupGLxXSK2n8s',
    appId: '1:930766606135:android:edaab80c0901e9b06d94b2',
    messagingSenderId: '930766606135',
    projectId: 'sirada-skripsi',
    storageBucket: 'sirada-skripsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX6uMKP1mSqN4Wr1_YqXnHfMDdjcLd5W8',
    appId: '1:930766606135:ios:6493082a03d9e86c6d94b2',
    messagingSenderId: '930766606135',
    projectId: 'sirada-skripsi',
    storageBucket: 'sirada-skripsi.appspot.com',
    iosClientId: '930766606135-nnu2tfbtgor31br0qcrkkof4noi8knpd.apps.googleusercontent.com',
    iosBundleId: 'com.tugasakhir.surat',
  );
}
